load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
    name = "0334",
    srcs = ["0334.cc"]
)

cc_binary(
    name = "0335",
    srcs = ["0335.cc"]
)

cc_binary(
    name = "0336",
    srcs = ["0336.cc"]
)

cc_binary(
    name = "0337",
    srcs = ["0337.cc"]
)
