cc_binary(
    name = "0501",
    srcs = ["0501.cc"]
)

cc_binary(
    name = "0502",
    srcs = ["0502.cc"],
    copts = ["-std=c++11"]
)

cc_binary(
    name = "0503",
    srcs = ["0503.cc"],
    copts = ["-std=c++11"]
)

cc_binary(
    name = "0504",
    srcs = ["0504.cc"]
)

cc_binary(
    name = "0505",
    srcs = ["0505.cc"],
    copts = ["-std=c++11"]
)

cc_binary(
    name = "0506",
    srcs = ["0506.cc"],
    copts = ["-std=c++11"]
)

cc_binary(
    name = "0507",
    srcs = ["0507.cc"],
    copts = ["-std=c++11"]
)
