cc_binary(
    name = "0508",
    srcs = ["0508.cc"],
    copts = ["-std=c++11"]
)

cc_binary(
    name = "0509",
    srcs = ["0509.cc"],
    copts = ["-std=c++11"]
)

cc_binary(
    name = "0510",
    srcs = ["0510.cc"]
)

cc_binary(
    name = "0511",
    srcs = ["0511.cc"]
)

cc_binary(
    name = "0512",
    srcs = ["0512.cc"]
)
